GRPCPort: 10003
GRPCHost: "zpd-service-3"
ID: 3
log:
  #PANNIC, FATAL, ERROR, WARN, INFO, DEBUG, TRACE
  level: "ERROR"
  isLogFile: false
  pathLogFile: "./logFile.log"
database:
  - hostPD: "pd1:2379"
  - hostPD: "pd2:2379"
  - hostPD: "pd3:23790"
consul:
  addressConsul: "consul:8500"
  ID: "ZPD_3" 
  name: "ZPD-SQLServer_3"
  tag: "ZPD-SQLServer"
  GRPCPort: 10003
  GRPCHost: "zpd-service-3"
  interval: 2
  deregisterCriticalServiceAfter: 10
  sessionTimeout: "10s"
  keyLeader: "service/zpd/leader"
bridge:
  poolSize: 100
  timeOut:  120